name: CI

# Trigger the workflow on push or pull request
on:
  [ pull_request, push ]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "8.8"
          - "8.10"
          - "9.0"
          - "9.2"
          - "9.4"
          - "9.6"
          - "9.8"
          - "9.10"
          - "9.12"
          - "latest"

    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/setup@v2
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}

    - uses: actions/cache@v4
      name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Build
      run: |
        cabal v2-update
        cabal v2-build --enable-tests --enable-benchmarks

    - name: Test
      run: |
        cabal v2-test --enable-tests
